_target_: src.models.components.timesformer.TimeSformer

dim: 512
num_frames: ${datamodule.num_frames}
image_size: ${datamodule.image_size}
patch_size: 16
channels: 3
depth: 12
heads: 8
dim_head: 64
attn_dropout: 0.
ff_dropout: 0.
rotary_emb: True
shift_tokens: False