_target_: src.models.components.AudioModel.Conformer

num_classes: ${model.num_classes} 
input_dim: 80
encoder_dim: 512
num_layers: 17
num_attention_heads: 8
feed_forward_expansion_factor: 4
conv_expansion_factor: 2
input_dropout_p: 0.1
feed_forward_dropout_p:  0.1
attention_dropout_p:  0.1
conv_dropout_p: 0.1
conv_kernel_size: 31
half_step_residual: True
pretrain_ckpt: null