_target_: src.models.components.timesformer.MetaTimesformer

img_size: ${datamodule.image_size}
patch_size: 16
num_classes: ${model.num_classes}
attention_type: 'divided_space_time'
pretrained_model: ""
num_frames: ${datamodule.num_frames}