# @package _global_

defaults:
  - /model/model/hubert@model.model1.model
  - /model/optim/adam@model.model1.optim

  - /model/model/roberta@model.model2.model
  - /model/optim/adamw@model.model2.optim
  - model.model2.scheduler: null
  - /model/optim/adam@model.aligner_optim
  - override /model: bi

model:
  link_mode: sync
  modality: at
  _target_: src.models.bi_module_skip.BiModule

  model1:
    scheduler: null
  unfreeze_epoch: 10
  exchange_levels:
    - [0, True, True]
    - [-1, True, True]

datamodule:
  spec_aug: True
  # max_audio_len: 500000
  # max_audio_len: 300000
  max_audio_len: 200000
  audio_format: raw
  cache_dir: ${data_dir}/cache/raw
  use_smart_sampler: False

trainer:
  gradient_clip_val: null
  accumulate_grad_batches: null

callbacks:
  early_stopping:
    patience: 20