# @package _global_

defaults:
  - /model/model/plain_video@model.video_model.model
  - /model/optim/adam@model.video_model.optim
  - /model/scheduler/stepLR@model.video_model.scheduler

  - /model/model/plain_transformer@model.text_model.model
  - /model/optim/adamw@model.text_model.optim
  - model.text_model.scheduler: null
  - override /model: multistage_vt
  - override /model/model/out@model.video_model.model.out: clfout
  - override /model/model/backbone@model.video_model.model.backbone: timesformer

model:
  link_mode: TCP

datamodule:
  data_dir: ${data_dir}/MSP-IMPROV