# @package _global_


defaults:
  - override /model: text
  - override /model/scheduler: null
  - override /model/optim: adamw
  - override /model/model: roberta

model:
  model:
    arch_name: bert-base-uncased