_target_: src.models.bi_module.BiModule

model1:
  model: ???
  optim: ???
  scheduler: ???
  weight: 1.0
  # if set, get best ckpt from wandb
  # <project>:<id>
  wandb_path: null

model2:
  model: ???
  optim: ???
  scheduler: null
  weight: 1.0
  wandb_path: null

aligner_optim: ???
link_mode: ???
exchange_levels: ???

modality: ???
task: ${datamodule.task}
init: null
num_classes: ${datamodule.num_classes}
stage: singlestage
dataset: ${datamodule.dataset}
accumulate_grad_batches: 1