_target_: src.datamodules.cmu_mosei_datamodule.DataModule

task: clf
fold: 1
modality: ${model.modality}
dataset: cmu_mosei
num_classes: 7
# dataset
data_dir: ${data_dir}/CMU-MOSEI
csv_dir: ${csv_dir}/CMU-MOSEI

# dataloader
batch_size: 32
num_workers: 1
pin_memory: True