_target_: src.datamodules.iemocap_datamodule.DataModule

task: clf
num_classes: 4
dataset: iemocap
fold: 1
modality: ${model.modality}
# dataset
data_dir: ${data_dir}/IEMOCAP
csv_dir: ${csv_dir}/IEMOCAP

# dataloader
batch_size: 32
num_workers: 1
pin_memory: True