_target_: src.datamodules.msp_improv_datamodule.DataModule

task: clf
num_classes: 4
dataset: msp_improv
fold: 1
modality: ${model.modality}
# dataset
data_dir: ${data_dir}/MSP-IMPROV
csv_dir: ${csv_dir}/MSP-IMPROV_12fold

# dataloader
batch_size: 32
num_workers: 1
pin_memory: True