# @package _global_

# to execute this experiment run:
# python run.py exp=<name>

##########
# L1 loss
##########

defaults:
  - override /datamodule: cmu_mosei.yaml
datamodule:
  task: clf
  num_classes: 7
model:
  num_classes: 1
# all parameters below will be merged with parameters from default configurations set above
# this allows you to overwrite only specified parameters

# name of the run determines folder name in logs
# can also be accessed by loggers
name: CMU-MOSEI

seed: 12345