# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python run.py -m hparams_search=mnist_optuna experiment=example_simple hydra.sweeper.n_trials=30

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "valid/WA"

datamodule:
  fold: 1

hydra:
  # here we define Optuna hyperparameter search
  # it optimizes for value returned from function with @hydra.main decorator
  # learn more here: https://hydra.cc/docs/next/plugins/optuna_sweeper
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # number of experiments that will be executed
    n_trials: 100

    # choose Optuna hyperparameter sampler
    # learn more here: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 12345
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    # define range of hyperparameters
    search_space:
      model.model1.optim.lr:
        type: float
        low: 1E-6
        high: 1E-4
        log: True
      model.model1.optim.weight_decay:
        type: float
        low: 0
        high: 1E-2
      model.model2.optim.lr:
        type: float
        low: 1E-6
        high: 1E-4
        log: True
      model.model2.optim.weight_decay:
        type: float
        low: 0
        high: 1E-2
      model.aligner_optim.lr:
        type: float
        low: 1E-6
        high: 1E-4
        log: True
      model.accumulate_grad_batches:
        type: categorical
        choices: [1, 2, 4]